package PrideBot.DND;

public class FishList {
    protected static String[] FISH = {
            "Trout",
            "Salmon",
            "Goldfish",
            "Sunfish",
            "Angler Fish",
            "Leech",
            "Piranha",
            "Shrimp",
            "Swordfish",
            "Tuna",
            "Herring",
            "Eel",
            "Sea Cucumber",
            "Lionfish",
            "Pufferfish",
            "Sea Nettle",
            "Moon Jelly",
            "Red Crab",
            "Blue Whale",
            "Orca",
            "Bottlenose Dolphin",
            "Guppy",
            "Minnow",
            "Water Elemental",
            "Largemouth Bass",
            "Catfish",
            "Giant Red Octopus",
            "Blueringed Octopus",
            "Kraken",
            "Giant Squid",
            "Blobfish",
            "Amazon Dolphin",
            "Betta",
            "Neon",
            "Blue Tuna",
            "Mackerel",
            "Lemon Shark",
            "Great White Shark",
            "Hammerhead Shark",
            "Whale Shark",
            "Krill",
            "Starfish",
            "Plankton",
            "Lamprey",
            "Remora",
            "Giant Koi",
            "Thresher Shark",
            "Mako Shark",
            "Megalodon",
            "Sailfish",
            "Bull Shark",
            "Anchovy",
            "Flying Fish",
            "Vampire Squid",
            "Blue Crab",
            "Lobster",
            "Sea Bass",
            "Mullet",
            "Sea Slug",
            "Mahi-Mahi",
            "Clownfish",
            "Sea Urchin",
            "Haddock",
            "Beluga Whale",
            "Angelfish",
            "Pike",
            "Squirrelfish",
            "Musselcracker",
            "Leopard Shark",
            "Tilapia",
            "Triggerfish",
            "Whaleshark",
            "Pollock",
            "Ocean Sunfish",
            "Black Drum",
            "Common Pandora",
            "Coral Trout",
            "Dogfish",
            "Ladyfish",
            "Grouper",
            "Bluefin Tuna",
            "Toadfish",
            "Blackfin Tuna",
            "Halibut",
            "White Bass",
            "Catfish",
            "Golden Dorado",
            "Paddlefish",
            "Sockeye Salmon",
            "Spotted Seatrout",
            "Trevally",
            "Hogfish",
            "Black Jewelfish",
            "Carp",
            "Sheepshead",
            "Whiting",
            "Cod",
            "White Marlin",
            "Pompano",
            "Wahoo",
            "Jack Crevalle",
            "Blue Marlin",
            "Roosterfish",
            "Parrotfish",
            "Vermillion Snapper",
            "White Grunt",
            "Crayfish",
            "Jobfish",
            "Red Snapper",
            "Tarpon",
            "Tantog",
            "Mako Shark",
            "Leerfish",
            "Pigfish",
            "Weakfish",
            "Yellowtail Snapper",
            "Tigerfish",
            "Butterfly Fish",
            "Bluefish",
            "Scorpionfish",
            "Rusty Jobfish",
            "Lingcod",
            "Rockfish",
            "Snailfish",
            "Nurse Shark",
            "Hammerhead",
            "Bonnethead Shark",
            "Bigeye Tuna",
            "Pinfish",
            "Shad",
            "Rainbow Trout",
            "Scallop",
            "Barramundi",
            "Penisfish",
            "Peacock Bass",
            "Queen Snapper",
            "Cardinal Fish",
            "Bonito",
            "Hapuka",
            "Sanger",
            "Mandarin Fish",
            "Bream",
            "Little Tunny",
            "Searobin",
            "Flatfish",
            "Chum Salmon",
            "Spearfish",
            "Butterfish",
            "Alligator Gar",
            "Cobia",
            "Snakehead",
            "Basselet",
            "Pejerry",
            "Kahawai",
            "Flying Fish",
            "Dhutfish",
            "Pink Maomao",
            "Pike Perch",
            "Barracuda",
            "Dolly Varden",
            "Tilefish",
            "Marlin",
            "Sturgeon",
            "Crappie",
            "Electric Eel",
            "Walleye Fish",
            "Sea Snail",
            "Stingrays",
            "Mantarays",
            "Seahorse",
            "Frogfish",
            "Handfish",
            "Batfish",
            "Vaiperfish",
            "Lanternfish",
            "Barreleye",
            "Wolffish",
            "Black Swallow",
            "Fangtooth",
            "Oarfish",
            "Knifefish",
            "Bluegill",
            "Gar",
            "Spidercrab",
            "Reaper Leviathan"
    };
}
